"""SQLAlchemy declarative base and shared column helpers.

Conventions enforced here (and relied upon by the Alembic autogenerate setup):

* every constraint has a deterministic name via ``naming_convention`` so that
  migrations reference constraints stably instead of by autogenerated name;
* every table uses a non-sequential UUIDv4 primary key, which is safe to expose
  publicly because it carries 122 bits of entropy and cannot be enumerated;
* timestamps are timezone-aware ``TIMESTAMP WITH TIME ZONE``;
* enums are stored as ``VARCHAR`` plus a CHECK constraint rather than native
  PostgreSQL enum types, so that adding a value is an ordinary, reversible
  migration instead of ``ALTER TYPE`` surgery.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
import uuid

from sqlalchemy import CheckConstraint, DateTime, Enum as SAEnum, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic constraint naming. Alembic autogeneration depends on this.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def utcnow() -> datetime:
    """Timezone-aware ``now`` used as the Python-side column default.

    Always called through this helper so no naive datetime can enter the
    codebase (enforced in CI by ruff's ``DTZ`` rules).
    """
    return datetime.now(UTC)


def new_uuid() -> uuid.UUID:
    """Generate a UUIDv4 primary key.

    ``uuid4`` rather than ``uuid1``: version 1 leaks timestamp and MAC-derived
    information, which would make identifiers partially guessable.
    """
    return uuid.uuid4()


class Base(DeclarativeBase):
    """Declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"


#: Mixin providing a UUIDv4 primary key.
class UUIDPrimaryKeyMixin:
    """Adds a non-sequential, publicly safe ``id`` column."""

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=new_uuid,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )


#: Mixin providing creation and modification timestamps.
class TimestampMixin:
    """Adds timezone-aware ``created_at`` / ``updated_at`` columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
        server_default=func.now(),
        nullable=False,
    )


def enum_values(values: type[Any]) -> list[str]:
    """Return the string values of a ``StrEnum`` for CHECK constraint building."""
    return [str(member.value) for member in values]


def install_enum_checks(metadata: MetaData) -> None:
    """Attach a CHECK constraint to every enum-typed column in ``metadata``.

    Rather than repeating ``enum_check(...)`` across twenty ``__table_args__``
    tuples - where one omission would silently allow an invalid status - the
    constraints are derived from the column types themselves. A column therefore
    cannot become an enum without simultaneously becoming constrained.

    Called once at the end of :mod:`app.db.models`, after every model has been
    imported, so it sees the complete metadata.
    """
    for table in metadata.tables.values():
        for column in table.columns:
            if not isinstance(column.type, SAEnum):
                continue
            constraint_name = f"{table.name}_{column.name}_valid"
            if any(existing.name == constraint_name for existing in table.constraints):
                continue
            allowed = ", ".join(f"'{value}'" for value in column.type.enums)
            table.append_constraint(
                CheckConstraint(
                    f"{column.name} IN ({allowed})",
                    name=constraint_name,
                )
            )
