"""Database-level guarantees that application code cannot provide.

These objects live outside the autogenerated migration body so that they are
easy to review, diff and test. Every function here is executed by a migration
inside the same transaction as the DDL it protects, so a failure rolls back
cleanly and the schema is never left half-hardened.

Design rule: **if a rule matters enough to be enforced, enforce it in the
database too.** Application-layer checks are the first line; these are the
second.
"""

from __future__ import annotations

from sqlalchemy import text
from sqlalchemy.engine import Connection

#: Raises on any attempt to rewrite the audit trail.
PREVENT_AUDIT_LOG_MUTATION_FN = """
CREATE OR REPLACE FUNCTION prevent_audit_log_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only; % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""

CREATE_AUDIT_LOG_GUARD_TRIGGER = """
-- DROP first so the statement is idempotent. A migration that is re-applied, or
-- that failed after this step and is retried, must not fail on DuplicateObject.
DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs;

CREATE TRIGGER audit_logs_append_only
BEFORE UPDATE OR DELETE ON audit_logs
FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
"""

DROP_AUDIT_LOG_GUARD_TRIGGER = "DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs;"

DROP_AUDIT_LOG_MUTATION_FN = "DROP FUNCTION IF EXISTS prevent_audit_log_mutation();"

#: The application lower-cases every address before writing. These constraints
#: make that invariant hold for *all* writers - seed scripts, admin tooling, a
#: future service, or a direct psql session - instead of relying on each call
#: site remembering to normalise.
_LOWERCASE_EMAIL_CONSTRAINTS: tuple[tuple[str, str], ...] = (
    ("users", "ck_users_email_lowercase"),
    ("verification_requests", "ck_verification_requests_verifier_email_lowercase"),
    ("worker_references", "ck_worker_references_email_lowercase"),
)

_AVAILABILITY_CHECK_DROP = """
ALTER TABLE worker_profiles
DROP CONSTRAINT IF EXISTS ck_worker_profiles_available_from_required
"""

_AVAILABILITY_CHECK = """
ALTER TABLE worker_profiles
ADD CONSTRAINT ck_worker_profiles_available_from_required
CHECK (availability_status <> 'AVAILABLE_SOON' OR available_from IS NOT NULL)
"""


def create_append_only_audit_guard(connection: Connection) -> None:
    """Install the trigger that makes ``audit_logs`` immutable.

    The application offers no update or delete endpoint, but the absence of an
    endpoint is not a control: a compromised service account or a manual ``psql``
    session must not be able to erase evidence either. ``FOR EACH ROW`` means
    the guard fires even for a multi-row statement.
    """
    connection.execute(text(PREVENT_AUDIT_LOG_MUTATION_FN))
    connection.execute(text(CREATE_AUDIT_LOG_GUARD_TRIGGER))


def drop_append_only_audit_guard(connection: Connection) -> None:
    """Remove the guard. Only ever used by a downgrade."""
    connection.execute(text(DROP_AUDIT_LOG_GUARD_TRIGGER))
    connection.execute(text(DROP_AUDIT_LOG_MUTATION_FN))


def add_lowercase_email_constraints(connection: Connection) -> None:
    """Forbid mixed-case addresses so uniqueness is genuinely case-insensitive."""
    for table, constraint in _LOWERCASE_EMAIL_CONSTRAINTS:
        connection.execute(
            text(
                f"ALTER TABLE {table} ADD CONSTRAINT {constraint} "
                f"CHECK ({_EMAIL_COLUMN[table]} = lower({_EMAIL_COLUMN[table]}))"
            )
        )


def drop_lowercase_email_constraints(connection: Connection) -> None:
    for table, constraint in _LOWERCASE_EMAIL_CONSTRAINTS:
        connection.execute(text(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {constraint}"))


def add_availability_consistency_check(connection: Connection) -> None:
    """``AVAILABLE_SOON`` without a start date is meaningless to an employer.

    Catching it here means a bug in one code path cannot publish a profile that
    an employer would read as "no idea when".
    """
    connection.execute(text(_AVAILABILITY_CHECK_DROP))
    connection.execute(text(_AVAILABILITY_CHECK))


def drop_availability_consistency_check(connection: Connection) -> None:
    connection.execute(
        text(
            "ALTER TABLE worker_profiles DROP CONSTRAINT IF EXISTS "
            "ck_worker_profiles_available_from_required"
        )
    )


#: Table -> the column holding the lower-cased address. Explicit rather than
#: interpolated from caller input.
_EMAIL_COLUMN: dict[str, str] = {
    "users": "email",
    "verification_requests": "verifier_email",
    "worker_references": "email",
}
