"""initial schema

Revision ID: 19e2bb154733
Revises:
Created: 2026-10-02 21:03:24.070432
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db import guards

revision: str = "19e2bb154733"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counties",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=True),
        sa.Column("capital", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_counties")),
        sa.UniqueConstraint("code", name="uq_counties_code"),
    )
    op.create_index(op.f("ix_counties_created_at"), "counties", ["created_at"], unique=False)
    op.create_table(
        "job_sources",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "PLATFORM",
                "EMPLOYER_SUBMITTED",
                "AGGREGATED_PUBLIC",
                "PARTNER_FEED",
                name="job_source_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=512), nullable=True),
        sa.Column(
            "terms_status",
            sa.Enum(
                "UNKNOWN",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "PROHIBITED",
                name="job_source_terms_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "robots_status",
            sa.Enum(
                "UNKNOWN",
                "PERMITTED",
                "RESTRICTED",
                "DISALLOWED",
                name="job_source_robots_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("respect_robots", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("licensing_notes", sa.Text(), nullable=True),
        sa.Column("rate_limit_per_minute", sa.Integer(), server_default="10", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "robots_status IN ('UNKNOWN', 'PERMITTED', 'RESTRICTED', 'DISALLOWED')",
            name=op.f("ck_job_sources_job_sources_robots_status_valid"),
        ),
        sa.CheckConstraint(
            "source_type IN ('PLATFORM', 'EMPLOYER_SUBMITTED', 'AGGREGATED_PUBLIC', 'PARTNER_FEED')",
            name=op.f("ck_job_sources_job_sources_source_type_valid"),
        ),
        sa.CheckConstraint(
            "terms_status IN ('UNKNOWN', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PROHIBITED')",
            name=op.f("ck_job_sources_job_sources_terms_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_sources")),
        sa.UniqueConstraint("code", name="uq_job_sources_code"),
    )
    op.create_index(
        "ix_job_sources_active", "job_sources", ["is_active", "terms_status"], unique=False
    )
    op.create_index(op.f("ix_job_sources_created_at"), "job_sources", ["created_at"], unique=False)
    op.create_table(
        "trades",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="100", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("code", name="uq_trades_code"),
    )
    op.create_index("ix_trades_active", "trades", ["is_active"], unique=False)
    op.create_index(op.f("ix_trades_created_at"), "trades", ["created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("WORKER", "EMPLOYER", "ADMIN", name="user_role", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "DEACTIVATED",
                name="account_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('WORKER', 'EMPLOYER', 'ADMIN')", name=op.f("ck_users_users_role_valid")
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')",
            name=op.f("ck_users_users_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
        comment="Authentication identity for workers, employers and admins.",
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index("ix_users_role_active", "users", ["role", "is_active"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN_SUCCESS",
                "LOGIN_FAILURE",
                "LOGIN_BLOCKED_LOCKED",
                "LOGOUT",
                "TOKEN_REFRESHED",
                "TOKEN_REUSE_DETECTED",
                "PASSWORD_CHANGED",
                "PASSWORD_RESET_REQUESTED",
                "PASSWORD_RESET_COMPLETED",
                "ACCOUNT_REGISTERED",
                "EMAIL_VERIFICATION_REQUESTED",
                "EMAIL_VERIFIED",
                "ACCOUNT_DISABLED",
                "ACCOUNT_DEACTIVATED",
                "ACCOUNT_ANONYMISED",
                "ROLE_CHANGED",
                "ADMIN_ACTION",
                "MEMBERSHIP_ADDED",
                "MEMBERSHIP_REMOVED",
                "MEMBERSHIP_ROLE_CHANGED",
                "VERIFICATION_REQUESTED",
                "VERIFICATION_COMPLETED",
                "VERIFICATION_REJECTED",
                "VERIFICATION_CANCELLED",
                "VERIFICATION_REVOKED",
                "FILE_UPLOADED",
                "FILE_ACCESSED",
                "FILE_DOWNLOAD_URL_ISSUED",
                "FILE_DELETED",
                "FILE_ACCESS_DENIED",
                "JOB_CREATED",
                "JOB_UPDATED",
                "JOB_STATUS_CHANGED",
                "JOB_SOURCE_REGISTERED",
                "JOB_INGESTED",
                "APPLICATION_SUBMITTED",
                "APPLICATION_STATUS_CHANGED",
                "APPLICATION_WITHDRAWN",
                "CATALOGUE_ITEM_CREATED",
                "CATALOGUE_ITEM_UPDATED",
                "CONTENT_REPORTED",
                "REPORT_RESOLVED",
                "CONTACT_REQUESTED",
                name="audit_action",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "action IN ('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGIN_BLOCKED_LOCKED', 'LOGOUT', 'TOKEN_REFRESHED', 'TOKEN_REUSE_DETECTED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ACCOUNT_REGISTERED', 'EMAIL_VERIFICATION_REQUESTED', 'EMAIL_VERIFIED', 'ACCOUNT_DISABLED', 'ACCOUNT_DEACTIVATED', 'ACCOUNT_ANONYMISED', 'ROLE_CHANGED', 'ADMIN_ACTION', 'MEMBERSHIP_ADDED', 'MEMBERSHIP_REMOVED', 'MEMBERSHIP_ROLE_CHANGED', 'VERIFICATION_REQUESTED', 'VERIFICATION_COMPLETED', 'VERIFICATION_REJECTED', 'VERIFICATION_CANCELLED', 'VERIFICATION_REVOKED', 'FILE_UPLOADED', 'FILE_ACCESSED', 'FILE_DOWNLOAD_URL_ISSUED', 'FILE_DELETED', 'FILE_ACCESS_DENIED', 'JOB_CREATED', 'JOB_UPDATED', 'JOB_STATUS_CHANGED', 'JOB_SOURCE_REGISTERED', 'JOB_INGESTED', 'APPLICATION_SUBMITTED', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_WITHDRAWN', 'CATALOGUE_ITEM_CREATED', 'CATALOGUE_ITEM_UPDATED', 'CONTENT_REPORTED', 'REPORT_RESOLVED', 'CONTACT_REQUESTED')",
            name=op.f("ck_audit_logs_audit_logs_action_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_logs_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "files",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "WORK_EVIDENCE",
                "CREDENTIAL_DOCUMENT",
                "REFERENCE_DOCUMENT",
                "ORGANIZATION_LOGO",
                "REPORT_ATTACHMENT",
                name="file_purpose",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "scan_status",
            sa.Enum(
                "PENDING",
                "CLEAN",
                "INFECTED",
                "ERROR",
                name="scan_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_engine", sa.String(length=64), nullable=True),
        sa.Column("is_quarantined", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("access_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('WORK_EVIDENCE', 'CREDENTIAL_DOCUMENT', 'REFERENCE_DOCUMENT', 'ORGANIZATION_LOGO', 'REPORT_ATTACHMENT')",
            name=op.f("ck_files_files_purpose_valid"),
        ),
        sa.CheckConstraint(
            "scan_status IN ('PENDING', 'CLEAN', 'INFECTED', 'ERROR')",
            name=op.f("ck_files_files_scan_status_valid"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 26214400",
            name=op.f("ck_files_files_size_within_hard_cap"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_files_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("object_key", name="uq_files_object_key"),
    )
    op.create_index(op.f("ix_files_created_at"), "files", ["created_at"], unique=False)
    op.create_index(op.f("ix_files_deleted_at"), "files", ["deleted_at"], unique=False)
    op.create_index("ix_files_owner", "files", ["owner_user_id", "deleted_at"], unique=False)
    op.create_index("ix_files_purpose", "files", ["purpose"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("website_url", sa.String(length=512), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("county", sa.String(length=120), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_organizations_county_id_counties"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
        comment="Employers are organizations; users join via memberships.",
    )
    op.create_index("ix_organizations_active", "organizations", ["is_active"], unique=False)
    op.create_index("ix_organizations_county", "organizations", ["county"], unique=False)
    op.create_index(
        op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_refresh_sessions_token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_created_at"), "refresh_sessions", ["created_at"], unique=False
    )
    op.create_index("ix_refresh_sessions_family", "refresh_sessions", ["family_id"], unique=False)
    op.create_index(
        "ix_refresh_sessions_user_active",
        "refresh_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum(
                "USER",
                "WORKER_PROFILE",
                "ORGANIZATION",
                "JOB",
                "VERIFICATION",
                name="report_subject_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "FRAUD",
                "MISLEADING_INFORMATION",
                "SCAM",
                "INAPPROPRIATE_CONTENT",
                "HARASSMENT",
                "ILLEGAL_ACTIVITY",
                "OTHER",
                name="report_reason",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_REVIEW",
                "RESOLVED",
                "DISMISSED",
                "ACTIONED",
                name="report_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('FRAUD', 'MISLEADING_INFORMATION', 'SCAM', 'INAPPROPRIATE_CONTENT', 'HARASSMENT', 'ILLEGAL_ACTIVITY', 'OTHER')",
            name=op.f("ck_reports_reports_reason_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED', 'ACTIONED')",
            name=op.f("ck_reports_reports_status_valid"),
        ),
        sa.CheckConstraint(
            "subject_type IN ('USER', 'WORKER_PROFILE', 'ORGANIZATION', 'JOB', 'VERIFICATION')",
            name=op.f("ck_reports_reports_subject_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_reports_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "reporter_user_id", "subject_type", "subject_id", name="uq_reports_reporter_subject"
        ),
    )
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_index("ix_reports_status", "reports", ["status", "created_at"], unique=False)
    op.create_index("ix_reports_subject", "reports", ["subject_type", "subject_id"], unique=False)
    op.create_table(
        "security_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "PASSWORD_RESET",
                "EMAIL_VERIFICATION",
                name="token_purpose",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('PASSWORD_RESET', 'EMAIL_VERIFICATION')",
            name=op.f("ck_security_tokens_security_tokens_purpose_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_security_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_security_tokens_token_hash"),
    )
    op.create_index(
        op.f("ix_security_tokens_created_at"), "security_tokens", ["created_at"], unique=False
    )
    op.create_index(
        "ix_security_tokens_user_purpose", "security_tokens", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "skills",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="100", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_skills_trade_id_trades"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("code", name="uq_skills_code"),
    )
    op.create_index(op.f("ix_skills_created_at"), "skills", ["created_at"], unique=False)
    op.create_index("ix_skills_trade_active", "skills", ["trade_id", "is_active"], unique=False)
    op.create_table(
        "worker_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("headline", sa.String(length=160), nullable=True),
        sa.Column("primary_trade_id", sa.Uuid(), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "self_declared_experience_years", sa.Numeric(precision=4, scale=1), nullable=True
        ),
        sa.Column(
            "availability_status",
            sa.Enum(
                "AVAILABLE",
                "AVAILABLE_SOON",
                "CURRENTLY_WORKING",
                "NOT_AVAILABLE",
                name="availability_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("available_from", sa.Date(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum(
                "PRIVATE",
                "DISCOVERABLE",
                "PUBLIC",
                name="profile_visibility",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "contact_preference",
            sa.Enum(
                "NONE",
                "IN_APP",
                "EMAIL",
                "PHONE",
                name="contact_preference",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("is_open_to_opportunities", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_name", sa.String(length=120), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "availability_status IN ('AVAILABLE', 'AVAILABLE_SOON', 'CURRENTLY_WORKING', 'NOT_AVAILABLE')",
            name=op.f("ck_worker_profiles_worker_profiles_availability_status_valid"),
        ),
        sa.CheckConstraint(
            "contact_preference IN ('NONE', 'IN_APP', 'EMAIL', 'PHONE')",
            name=op.f("ck_worker_profiles_worker_profiles_contact_preference_valid"),
        ),
        sa.CheckConstraint(
            "visibility IN ('PRIVATE', 'DISCOVERABLE', 'PUBLIC')",
            name=op.f("ck_worker_profiles_worker_profiles_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_worker_profiles_county_id_counties"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["primary_trade_id"],
            ["trades.id"],
            name=op.f("fk_worker_profiles_primary_trade_id_trades"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_worker_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_profiles")),
        sa.UniqueConstraint("user_id", name="uq_worker_profiles_user_id"),
        comment="One Work Passport per user account.",
    )
    op.create_index(
        "ix_worker_profiles_availability", "worker_profiles", ["availability_status"], unique=False
    )
    op.create_index("ix_worker_profiles_county", "worker_profiles", ["county_id"], unique=False)
    op.create_index(
        op.f("ix_worker_profiles_created_at"), "worker_profiles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_profiles_deleted_at"), "worker_profiles", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_worker_profiles_primary_trade", "worker_profiles", ["primary_trade_id"], unique=False
    )
    op.create_index(
        "ix_worker_profiles_visibility",
        "worker_profiles",
        ["visibility", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "credentials",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "credential_type",
            sa.Enum(
                "CERTIFICATE",
                "LICENCE",
                "ACADEMIC_QUALIFICATION",
                "TRADE_TEST_CERTIFICATE",
                "SAFETY_TRAINING",
                "FIRST_AID",
                "OTHER",
                name="credential_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.Column("issuing_country_code", sa.String(length=2), nullable=True),
        sa.Column("credential_number", sa.String(length=120), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "credential_type IN ('CERTIFICATE', 'LICENCE', 'ACADEMIC_QUALIFICATION', 'TRADE_TEST_CERTIFICATE', 'SAFETY_TRAINING', 'FIRST_AID', 'OTHER')",
            name=op.f("ck_credentials_credentials_credential_type_valid"),
        ),
        sa.CheckConstraint(
            "expiry_date IS NULL OR issue_date IS NULL OR expiry_date >= issue_date",
            name=op.f("ck_credentials_credentials_expiry_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_credentials_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_credentials_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
    )
    op.create_index(op.f("ix_credentials_created_at"), "credentials", ["created_at"], unique=False)
    op.create_index(op.f("ix_credentials_deleted_at"), "credentials", ["deleted_at"], unique=False)
    op.create_index(
        "ix_credentials_profile", "credentials", ["worker_profile_id", "deleted_at"], unique=False
    )
    op.create_index("ix_credentials_type", "credentials", ["credential_type"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "CONTRACT",
                "TEMPORARY",
                "CASUAL",
                "APPRENTICEHIP",
                "INTERNSHIP",
                name="employment_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "NOT_SPECIFIED",
                "ENTRY",
                "INTERMEDIATE",
                "EXPERIENCED",
                name="experience_level",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("experience_required_years", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "CLOSED",
                "CANCELLED",
                "EXPIRED",
                name="job_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "PLATFORM",
                "EMPLOYER_SUBMITTED",
                "AGGREGATED_PUBLIC",
                "PARTNER_FEED",
                name="job_source_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("source_job_id", sa.String(length=255), nullable=True),
        sa.Column("external_apply_url", sa.String(length=1024), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_aggregated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("salary_period", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'CASUAL', 'APPRENTICEHIP', 'INTERNSHIP')",
            name=op.f("ck_jobs_jobs_employment_type_valid"),
        ),
        sa.CheckConstraint(
            "experience_level IN ('NOT_SPECIFIED', 'ENTRY', 'INTERMEDIATE', 'EXPERIENCED')",
            name=op.f("ck_jobs_jobs_experience_level_valid"),
        ),
        sa.CheckConstraint(
            "source_type <> 'PLATFORM' OR source_job_id IS NULL",
            name=op.f("ck_jobs_jobs_platform_has_no_external_id"),
        ),
        sa.CheckConstraint(
            "source_type IN ('PLATFORM', 'EMPLOYER_SUBMITTED', 'AGGREGATED_PUBLIC', 'PARTNER_FEED')",
            name=op.f("ck_jobs_jobs_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status = 'DRAFT' OR organization_id IS NOT NULL",
            name=op.f("ck_jobs_jobs_published_requires_organization"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_jobs_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "closing_at IS NULL OR published_at IS NULL OR closing_at >= published_at",
            name=op.f("ck_jobs_jobs_closing_after_publish"),
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_jobs_county_id_counties"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["job_sources.id"],
            name=op.f("fk_jobs_source_id_job_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_jobs_trade_id_trades"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_county_status", "jobs", ["county_id", "status"], unique=False)
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_deleted_at"), "jobs", ["deleted_at"], unique=False)
    op.create_index("ix_jobs_external", "jobs", ["source_type", "last_seen_at"], unique=False)
    op.create_index("ix_jobs_organization", "jobs", ["organization_id", "status"], unique=False)
    op.create_index("ix_jobs_status_published", "jobs", ["status", "published_at"], unique=False)
    op.create_index("ix_jobs_trade_status", "jobs", ["trade_id", "status"], unique=False)
    op.create_index(
        "uq_jobs_source_external_id",
        "jobs",
        ["source_id", "source_job_id"],
        unique=True,
        postgresql_where=sa.text("source_job_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "organization_memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "RECRUITER",
                "MEMBER",
                name="organization_role",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INVITED",
                "SUSPENDED",
                name="membership_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'ADMIN', 'RECRUITER', 'MEMBER')",
            name=op.f("ck_organization_memberships_organization_memberships_role_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'INVITED', 'SUSPENDED')",
            name=op.f("ck_organization_memberships_organization_memberships_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_organization_memberships_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_organization_memberships_org_user"
        ),
        comment="Per-organization role; platform role is stored on users.role.",
    )
    op.create_index(
        "ix_org_memberships_user_status",
        "organization_memberships",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_created_at"),
        "organization_memberships",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project_type", sa.String(length=120), nullable=True),
        sa.Column("role_title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("work_performed", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_confidential", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_projects_projects_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_projects_county_id_counties"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_projects_trade_id_trades"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_projects_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index("ix_projects_county", "projects", ["county_id"], unique=False)
    op.create_index(op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False)
    op.create_index(op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False)
    op.create_index(
        "ix_projects_profile", "projects", ["worker_profile_id", "deleted_at"], unique=False
    )
    op.create_index("ix_projects_trade", "projects", ["trade_id"], unique=False)
    op.create_table(
        "verification_requests",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "PROJECT",
                "EXPERIENCE",
                "SKILL",
                "CREDENTIAL",
                "REFERENCE",
                name="verification_target_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("target_label", sa.String(length=255), nullable=True),
        sa.Column("target_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("verifier_email", sa.String(length=320), nullable=False),
        sa.Column("verifier_full_name", sa.String(length=160), nullable=True),
        sa.Column("verifier_organization_id", sa.Uuid(), nullable=True),
        sa.Column("verifier_relationship", sa.String(length=160), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                name="verification_request_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("response_notes", sa.Text(), nullable=True),
        sa.Column("invitation_token_hash", sa.String(length=64), nullable=True),
        sa.Column("invitation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invitation_consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'VERIFIED', 'REJECTED', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_verification_requests_verification_requests_status_valid"),
        ),
        sa.CheckConstraint(
            "target_type IN ('PROJECT', 'EXPERIENCE', 'SKILL', 'CREDENTIAL', 'REFERENCE')",
            name=op.f("ck_verification_requests_verification_requests_target_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_verification_requests_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["responded_by_user_id"],
            ["users.id"],
            name=op.f("fk_verification_requests_responded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verifier_organization_id"],
            ["organizations.id"],
            name=op.f("fk_verification_requests_verifier_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_verification_requests_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_requests")),
    )
    op.create_index(
        op.f("ix_verification_requests_created_at"),
        "verification_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_verification_requests_invitation_token",
        "verification_requests",
        ["invitation_token_hash"],
        unique=False,
    )
    op.create_index(
        "ix_verification_requests_invitee",
        "verification_requests",
        ["verifier_email"],
        unique=False,
    )
    op.create_index(
        "ix_verification_requests_worker",
        "verification_requests",
        ["worker_profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_verification_requests_one_pending_per_target",
        "verification_requests",
        ["target_type", "target_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "work_experiences",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("employer_name", sa.String(length=255), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=True),
        sa.Column("role_title", sa.String(length=160), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("county_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(end_date IS NULL) != is_current",
            name=op.f("ck_work_experiences_work_experiences_current_matches_end_date"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_work_experiences_work_experiences_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_work_experiences_county_id_counties"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_work_experiences_trade_id_trades"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_work_experiences_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_experiences")),
    )
    op.create_index(
        op.f("ix_work_experiences_created_at"), "work_experiences", ["created_at"], unique=False
    )
    op.create_index(
        "ix_work_experiences_dates", "work_experiences", ["start_date", "end_date"], unique=False
    )
    op.create_index(
        op.f("ix_work_experiences_deleted_at"), "work_experiences", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_work_experiences_profile",
        "work_experiences",
        ["worker_profile_id", "deleted_at"],
        unique=False,
    )
    op.create_index("ix_work_experiences_trade", "work_experiences", ["trade_id"], unique=False)
    op.create_table(
        "worker_preferred_counties",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("county_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["county_id"],
            ["counties.id"],
            name=op.f("fk_worker_preferred_counties_county_id_counties"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_worker_preferred_counties_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_preferred_counties")),
        sa.UniqueConstraint(
            "worker_profile_id", "county_id", name="uq_worker_preferred_counties_profile_county"
        ),
    )
    op.create_index(
        "ix_worker_preferred_counties_county",
        "worker_preferred_counties",
        ["county_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_preferred_counties_created_at"),
        "worker_preferred_counties",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "worker_references",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "FOREMAN",
                "SUPERVISOR",
                "COLLEAGUE",
                "CLIENT",
                "CONTRACTOR",
                "PERSONAL",
                name="reference_relationship",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("organization_name", sa.String(length=255), nullable=True),
        sa.Column("job_title", sa.String(length=160), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_INVITATION",
                "CONFIRMED",
                "DECLINED",
                "REVOKED",
                name="reference_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("invitation_token_hash", sa.String(length=64), nullable=True),
        sa.Column("invitation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invitation_consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_statement", sa.Text(), nullable=True),
        sa.Column("responded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("is_visible_to_employers", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "relationship IN ('FOREMAN', 'SUPERVISOR', 'COLLEAGUE', 'CLIENT', 'CONTRACTOR', 'PERSONAL')",
            name=op.f("ck_worker_references_worker_references_relationship_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_INVITATION', 'CONFIRMED', 'DECLINED', 'REVOKED')",
            name=op.f("ck_worker_references_worker_references_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["responded_by_user_id"],
            ["users.id"],
            name=op.f("fk_worker_references_responded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_worker_references_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_references")),
        sa.UniqueConstraint(
            "worker_profile_id", "email", name="uq_worker_references_profile_email"
        ),
    )
    op.create_index(
        op.f("ix_worker_references_created_at"), "worker_references", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_references_deleted_at"), "worker_references", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_worker_references_invitation",
        "worker_references",
        ["invitation_token_hash"],
        unique=False,
    )
    op.create_index(
        "ix_worker_references_profile",
        "worker_references",
        ["worker_profile_id", "deleted_at"],
        unique=False,
    )
    op.create_index("ix_worker_references_status", "worker_references", ["status"], unique=False)
    op.create_table(
        "worker_skills",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column(
            "proficiency",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="skill_proficiency",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proficiency IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')",
            name=op.f("ck_worker_skills_worker_skills_proficiency_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_worker_skills_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_worker_skills_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_skills")),
        sa.UniqueConstraint("worker_profile_id", "skill_id", name="uq_worker_skills_profile_skill"),
    )
    op.create_index(
        op.f("ix_worker_skills_created_at"), "worker_skills", ["created_at"], unique=False
    )
    op.create_index(
        "ix_worker_skills_profile", "worker_skills", ["worker_profile_id"], unique=False
    )
    op.create_index("ix_worker_skills_skill", "worker_skills", ["skill_id"], unique=False)
    op.create_table(
        "worker_trades",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_worker_trades_trade_id_trades"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_worker_trades_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_trades")),
        sa.UniqueConstraint("worker_profile_id", "trade_id", name="uq_worker_trades_profile_trade"),
    )
    op.create_index(
        op.f("ix_worker_trades_created_at"), "worker_trades", ["created_at"], unique=False
    )
    op.create_index("ix_worker_trades_trade", "worker_trades", ["trade_id"], unique=False)
    op.create_index(
        "uq_worker_trades_single_primary",
        "worker_trades",
        ["worker_profile_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "evidence_items",
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("work_experience_id", sa.Uuid(), nullable=True),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum(
                "PRIVATE",
                "EMPLOYERS",
                "PUBLIC",
                name="evidence_visibility",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("captured_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "visibility IN ('PRIVATE', 'EMPLOYERS', 'PUBLIC')",
            name=op.f("ck_evidence_items_evidence_items_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
            name=op.f("fk_evidence_items_credential_id_credentials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_evidence_items_file_id_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evidence_items_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_experience_id"],
            ["work_experiences.id"],
            name=op.f("fk_evidence_items_work_experience_id_work_experiences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_evidence_items_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_index(
        op.f("ix_evidence_items_created_at"), "evidence_items", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_items_deleted_at"), "evidence_items", ["deleted_at"], unique=False
    )
    op.create_index("ix_evidence_items_file", "evidence_items", ["file_id"], unique=False)
    op.create_index(
        "ix_evidence_items_profile",
        "evidence_items",
        ["worker_profile_id", "deleted_at"],
        unique=False,
    )
    op.create_index("ix_evidence_items_project", "evidence_items", ["project_id"], unique=False)
    op.create_table(
        "job_applications",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("cover_note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "VIEWED",
                "SHORTLISTED",
                "REJECTED",
                "WITHDRAWN",
                "HIRED",
                name="application_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_status_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED', 'VIEWED', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN', 'HIRED')",
            name=op.f("ck_job_applications_job_applications_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_job_applications_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_applications_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_job_applications_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_applications")),
        sa.UniqueConstraint("job_id", "worker_profile_id", name="uq_job_applications_job_worker"),
    )
    op.create_index(
        op.f("ix_job_applications_created_at"), "job_applications", ["created_at"], unique=False
    )
    op.create_index(
        "ix_job_applications_job_status", "job_applications", ["job_id", "status"], unique=False
    )
    op.create_index(
        "ix_job_applications_status", "job_applications", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_job_applications_worker",
        "job_applications",
        ["worker_profile_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_job_applications_idempotency",
        "job_applications",
        ["worker_profile_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_skills_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_job_skills_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_skills")),
        sa.UniqueConstraint("job_id", "skill_id", name="uq_job_skills_job_skill"),
    )
    op.create_index(op.f("ix_job_skills_created_at"), "job_skills", ["created_at"], unique=False)
    op.create_index("ix_job_skills_skill", "job_skills", ["skill_id"], unique=False)
    op.create_table(
        "job_source_events",
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "NEW_JOB",
                "JOB_UPDATED",
                "DEADLINE_CHANGED",
                "JOB_CLOSED",
                "JOB_REMOVED",
                name="job_change_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('NEW_JOB', 'JOB_UPDATED', 'DEADLINE_CHANGED', 'JOB_CLOSED', 'JOB_REMOVED')",
            name=op.f("ck_job_source_events_job_source_events_change_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_source_events_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["job_sources.id"],
            name=op.f("fk_job_source_events_source_id_job_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_source_events")),
    )
    op.create_index(
        op.f("ix_job_source_events_created_at"), "job_source_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_job_source_events_job", "job_source_events", ["job_id", "detected_at"], unique=False
    )
    op.create_index(
        "ix_job_source_events_source",
        "job_source_events",
        ["source_id", "change_type"],
        unique=False,
    )
    op.create_table(
        "notification_events",
        sa.Column(
            "event_type",
            sa.Enum(
                "VERIFICATION_REQUESTED",
                "VERIFICATION_COMPLETED",
                "REFERENCE_INVITATION_SENT",
                "JOB_MATCH_FOUND",
                "APPLICATION_STATUS_CHANGED",
                "APPLICATION_WITHDRAWN",
                "EMPLOYER_CONTACT_REQUEST",
                "CONTENT_REPORTED",
                name="notification_event_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_email", sa.String(length=320), nullable=True),
        sa.Column("worker_profile_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('VERIFICATION_REQUESTED', 'VERIFICATION_COMPLETED', 'REFERENCE_INVITATION_SENT', 'JOB_MATCH_FOUND', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_WITHDRAWN', 'EMPLOYER_CONTACT_REQUEST', 'CONTENT_REPORTED')",
            name=op.f("ck_notification_events_notification_events_event_type_valid"),
        ),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR recipient_email IS NOT NULL",
            name=op.f("ck_notification_events_notification_events_has_recipient"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_notification_events_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_notification_events_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_events")),
    )
    op.create_index(
        op.f("ix_notification_events_created_at"),
        "notification_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_recipient",
        "notification_events",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_unprocessed",
        "notification_events",
        ["processed_at", "event_type"],
        unique=False,
    )
    op.create_table(
        "verifications",
        sa.Column("verification_request_id", sa.Uuid(), nullable=False),
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "PROJECT",
                "EXPERIENCE",
                "SKILL",
                "CREDENTIAL",
                "REFERENCE",
                name="verification_target_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "VERIFIED",
                "REJECTED",
                "REVOKED",
                name="verification_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verifier_display_name", sa.String(length=160), nullable=False),
        sa.Column("verifier_organization_id", sa.Uuid(), nullable=True),
        sa.Column("verifier_relationship", sa.String(length=160), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_summary", sa.Text(), nullable=True),
        sa.Column("response_statement", sa.Text(), nullable=True),
        sa.Column("is_visible_to_employers", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_reason", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'REVOKED') OR revoked_at IS NULL",
            name=op.f("ck_verifications_verifications_revoked_at_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('VERIFIED', 'REJECTED', 'REVOKED')",
            name=op.f("ck_verifications_verifications_status_valid"),
        ),
        sa.CheckConstraint(
            "target_type IN ('PROJECT', 'EXPERIENCE', 'SKILL', 'CREDENTIAL', 'REFERENCE')",
            name=op.f("ck_verifications_verifications_target_type_valid"),
        ),
        sa.CheckConstraint(
            "verified_by_user_id IS NULL OR verified_by_user_id <> requested_by_user_id",
            name=op.f("ck_verifications_verifications_no_self_verification"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_verifications_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["users.id"],
            name=op.f("fk_verifications_revoked_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verification_request_id"],
            ["verification_requests.id"],
            name=op.f("fk_verifications_verification_request_id_verification_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_verifications_verified_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verifier_organization_id"],
            ["organizations.id"],
            name=op.f("fk_verifications_verifier_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_verifications_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verifications")),
        sa.UniqueConstraint("verification_request_id", name="uq_verifications_request_id"),
    )
    op.create_index(
        op.f("ix_verifications_created_at"), "verifications", ["created_at"], unique=False
    )
    op.create_index(
        "ix_verifications_target", "verifications", ["target_type", "target_id"], unique=False
    )
    op.create_index(
        "ix_verifications_worker", "verifications", ["worker_profile_id", "status"], unique=False
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Hand-written guarantees layered on the autogenerated schema.
    # See app/db/guards.py for the reasoning behind each one.
    # ------------------------------------------------------------------
    _bind = op.get_bind()
    guards.create_append_only_audit_guard(_bind)
    guards.add_lowercase_email_constraints(_bind)
    guards.add_availability_consistency_check(_bind)


def downgrade() -> None:
    # Remove the guards before the tables they reference disappear.
    _bind = op.get_bind()
    guards.drop_availability_consistency_check(_bind)
    guards.drop_lowercase_email_constraints(_bind)
    guards.drop_append_only_audit_guard(_bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verifications_worker", table_name="verifications")
    op.drop_index("ix_verifications_target", table_name="verifications")
    op.drop_index(op.f("ix_verifications_created_at"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index("ix_notification_events_unprocessed", table_name="notification_events")
    op.drop_index("ix_notification_events_recipient", table_name="notification_events")
    op.drop_index(op.f("ix_notification_events_created_at"), table_name="notification_events")
    op.drop_table("notification_events")
    op.drop_index("ix_job_source_events_source", table_name="job_source_events")
    op.drop_index("ix_job_source_events_job", table_name="job_source_events")
    op.drop_index(op.f("ix_job_source_events_created_at"), table_name="job_source_events")
    op.drop_table("job_source_events")
    op.drop_index("ix_job_skills_skill", table_name="job_skills")
    op.drop_index(op.f("ix_job_skills_created_at"), table_name="job_skills")
    op.drop_table("job_skills")
    op.drop_index(
        "uq_job_applications_idempotency",
        table_name="job_applications",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_job_applications_worker", table_name="job_applications")
    op.drop_index("ix_job_applications_status", table_name="job_applications")
    op.drop_index("ix_job_applications_job_status", table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_created_at"), table_name="job_applications")
    op.drop_table("job_applications")
    op.drop_index("ix_evidence_items_project", table_name="evidence_items")
    op.drop_index("ix_evidence_items_profile", table_name="evidence_items")
    op.drop_index("ix_evidence_items_file", table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_deleted_at"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_created_at"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(
        "uq_worker_trades_single_primary",
        table_name="worker_trades",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index("ix_worker_trades_trade", table_name="worker_trades")
    op.drop_index(op.f("ix_worker_trades_created_at"), table_name="worker_trades")
    op.drop_table("worker_trades")
    op.drop_index("ix_worker_skills_skill", table_name="worker_skills")
    op.drop_index("ix_worker_skills_profile", table_name="worker_skills")
    op.drop_index(op.f("ix_worker_skills_created_at"), table_name="worker_skills")
    op.drop_table("worker_skills")
    op.drop_index("ix_worker_references_status", table_name="worker_references")
    op.drop_index("ix_worker_references_profile", table_name="worker_references")
    op.drop_index("ix_worker_references_invitation", table_name="worker_references")
    op.drop_index(op.f("ix_worker_references_deleted_at"), table_name="worker_references")
    op.drop_index(op.f("ix_worker_references_created_at"), table_name="worker_references")
    op.drop_table("worker_references")
    op.drop_index(
        op.f("ix_worker_preferred_counties_created_at"), table_name="worker_preferred_counties"
    )
    op.drop_index("ix_worker_preferred_counties_county", table_name="worker_preferred_counties")
    op.drop_table("worker_preferred_counties")
    op.drop_index("ix_work_experiences_trade", table_name="work_experiences")
    op.drop_index("ix_work_experiences_profile", table_name="work_experiences")
    op.drop_index(op.f("ix_work_experiences_deleted_at"), table_name="work_experiences")
    op.drop_index("ix_work_experiences_dates", table_name="work_experiences")
    op.drop_index(op.f("ix_work_experiences_created_at"), table_name="work_experiences")
    op.drop_table("work_experiences")
    op.drop_index(
        "uq_verification_requests_one_pending_per_target",
        table_name="verification_requests",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_verification_requests_worker", table_name="verification_requests")
    op.drop_index("ix_verification_requests_invitee", table_name="verification_requests")
    op.drop_index("ix_verification_requests_invitation_token", table_name="verification_requests")
    op.drop_index(op.f("ix_verification_requests_created_at"), table_name="verification_requests")
    op.drop_table("verification_requests")
    op.drop_index("ix_projects_trade", table_name="projects")
    op.drop_index("ix_projects_profile", table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_index("ix_projects_county", table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        op.f("ix_organization_memberships_created_at"), table_name="organization_memberships"
    )
    op.drop_index("ix_org_memberships_user_status", table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_index(
        "uq_jobs_source_external_id",
        table_name="jobs",
        postgresql_where=sa.text("source_job_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("ix_jobs_trade_status", table_name="jobs")
    op.drop_index("ix_jobs_status_published", table_name="jobs")
    op.drop_index("ix_jobs_organization", table_name="jobs")
    op.drop_index("ix_jobs_external", table_name="jobs")
    op.drop_index(op.f("ix_jobs_deleted_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index("ix_jobs_county_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_credentials_type", table_name="credentials")
    op.drop_index("ix_credentials_profile", table_name="credentials")
    op.drop_index(op.f("ix_credentials_deleted_at"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_created_at"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index("ix_worker_profiles_visibility", table_name="worker_profiles")
    op.drop_index("ix_worker_profiles_primary_trade", table_name="worker_profiles")
    op.drop_index(op.f("ix_worker_profiles_deleted_at"), table_name="worker_profiles")
    op.drop_index(op.f("ix_worker_profiles_created_at"), table_name="worker_profiles")
    op.drop_index("ix_worker_profiles_county", table_name="worker_profiles")
    op.drop_index("ix_worker_profiles_availability", table_name="worker_profiles")
    op.drop_table("worker_profiles")
    op.drop_index("ix_skills_trade_active", table_name="skills")
    op.drop_index(op.f("ix_skills_created_at"), table_name="skills")
    op.drop_table("skills")
    op.drop_index("ix_security_tokens_user_purpose", table_name="security_tokens")
    op.drop_index(op.f("ix_security_tokens_created_at"), table_name="security_tokens")
    op.drop_table("security_tokens")
    op.drop_index("ix_reports_subject", table_name="reports")
    op.drop_index("ix_reports_status", table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_refresh_sessions_user_active", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_family", table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_created_at"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_index("ix_organizations_county", table_name="organizations")
    op.drop_index("ix_organizations_active", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("ix_files_purpose", table_name="files")
    op.drop_index("ix_files_owner", table_name="files")
    op.drop_index(op.f("ix_files_deleted_at"), table_name="files")
    op.drop_index(op.f("ix_files_created_at"), table_name="files")
    op.drop_table("files")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_index("ix_audit_logs_request_id", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_users_role_active", table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_trades_created_at"), table_name="trades")
    op.drop_index("ix_trades_active", table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_job_sources_created_at"), table_name="job_sources")
    op.drop_index("ix_job_sources_active", table_name="job_sources")
    op.drop_table("job_sources")
    op.drop_index(op.f("ix_counties_created_at"), table_name="counties")
    op.drop_table("counties")
    # ### end Alembic commands ###

