"""add notifications inbox

Revision ID: 36eb48c08ad4
Revises: 38283c2185b9
Created: 2026-10-03 12:57:36.237350
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "36eb48c08ad4"
down_revision: str | None = "38283c2185b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "VERIFICATION_REQUESTED",
                "VERIFICATION_COMPLETED",
                "REFERENCE_INVITATION_SENT",
                "JOB_MATCH_FOUND",
                "APPLICATION_STATUS_CHANGED",
                "APPLICATION_WITHDRAWN",
                "EMPLOYER_CONTACT_REQUEST",
                "CONTENT_REPORTED",
                name="notification_event_type",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("related_resource_id", sa.Uuid(), nullable=True),
        sa.Column("related_resource_type", sa.String(length=40), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('VERIFICATION_REQUESTED', 'VERIFICATION_COMPLETED', 'REFERENCE_INVITATION_SENT', 'JOB_MATCH_FOUND', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_WITHDRAWN', 'EMPLOYER_CONTACT_REQUEST', 'CONTENT_REPORTED')",
            name=op.f("ck_notifications_notifications_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_recipient_unread",
        "notifications",
        ["recipient_user_id", "created_at"],
        unique=False,
        postgresql_where="read_at IS NULL",
    )
    op.create_index(
        "ix_notifications_related",
        "notifications",
        ["related_resource_type", "related_resource_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_related", table_name="notifications")
    op.drop_index(
        "ix_notifications_recipient_unread",
        table_name="notifications",
        postgresql_where="read_at IS NULL",
    )
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
