"""add contact_requests

Revision ID: 38283c2185b9
Revises: 51dc2c631da4
Created: 2026-10-03 12:45:55.844999
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "38283c2185b9"
down_revision: str | None = "51dc2c631da4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("worker_profile_id", sa.Uuid(), nullable=False),
        sa.Column("requester_user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                name="contact_request_status",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("response_note", sa.Text(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contact_details_shared", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'ACCEPTED' OR responded_at IS NOT NULL",
            name=op.f("ck_contact_requests_contact_requests_accepted_needs_response"),
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR responded_at IS NOT NULL",
            name=op.f("ck_contact_requests_contact_requests_cancelled_needs_response"),
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' OR responded_at IS NOT NULL",
            name=op.f("ck_contact_requests_contact_requests_rejected_needs_response"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_contact_requests_contact_requests_status_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(message)) BETWEEN 1 AND 1000",
            name=op.f("ck_contact_requests_contact_requests_message_length"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_contact_requests_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_contact_requests_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
            name=op.f("fk_contact_requests_requester_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_profile_id"],
            ["worker_profiles.id"],
            name=op.f("fk_contact_requests_worker_profile_id_worker_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_requests")),
        sa.UniqueConstraint(
            "requester_user_id",
            "worker_profile_id",
            "job_id",
            name="uq_contact_requests_requester_worker_job",
        ),
    )
    op.create_index(
        op.f("ix_contact_requests_created_at"), "contact_requests", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_contact_requests_deleted_at"), "contact_requests", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_contact_requests_requester",
        "contact_requests",
        ["requester_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_contact_requests_worker_status",
        "contact_requests",
        ["worker_profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_contact_requests_one_pending_per_worker",
        "contact_requests",
        ["worker_profile_id", "requester_user_id"],
        unique=True,
        postgresql_where="status = 'PENDING' AND deleted_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_contact_requests_one_pending_per_worker",
        table_name="contact_requests",
        postgresql_where="status = 'PENDING' AND deleted_at IS NULL",
    )
    op.drop_index("ix_contact_requests_worker_status", table_name="contact_requests")
    op.drop_index("ix_contact_requests_requester", table_name="contact_requests")
    op.drop_index(op.f("ix_contact_requests_deleted_at"), table_name="contact_requests")
    op.drop_index(op.f("ix_contact_requests_created_at"), table_name="contact_requests")
    op.drop_table("contact_requests")
    # ### end Alembic commands ###
