#!/usr/bin/env python3
"""Resolve and pin the dependency closure for the FundiPulse API.

The project declares direct dependencies as ranges in ``requirements/*.in``.
Reproducible builds need exact versions, so this script walks the installed
distribution metadata to compute the full transitive closure and writes a
pinned ``requirements/*.txt`` for each target environment.

It intentionally uses only ``importlib.metadata`` (no network access) so it can
run inside CI against whatever was already installed by ``pip install -r``.

Usage:
    python scripts/lock_requirements.py

Exit codes:
    0  locks written
    1  a declared requirement is not satisfied by the current environment
"""

from __future__ import annotations

from collections.abc import Iterator
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path
import re
import sys

from packaging.requirements import InvalidRequirement, Requirement

REPO_ROOT = Path(__file__).resolve().parent.parent

REQUIREMENT_RE = re.compile(
    r"""
    ^\s*(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)
    (?:\[[^\]]*\])?
    \s*
    (?:\((?P<version>[^)]*)\))?
    """,
    re.VERBOSE,
)


def canonical(name: str) -> str:
    """PEP 503 normalisation."""
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_direct_requirements(path: Path, _seen: set[Path] | None = None) -> list[str]:
    """Return canonical distribution names declared in an ``.in`` file.

    Follows ``-r``/``--requirement`` includes recursively. ``dev.in`` includes
    ``base.in``; skipping those would produce a ``dev.txt`` containing the test
    tooling but silently omitting the application itself - a lock file that
    installs cleanly and then fails at import time.
    """
    seen = _seen if _seen is not None else set()
    resolved_path = path.resolve()
    if resolved_path in seen:
        return []
    seen.add(resolved_path)

    names: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith(("-r ", "--requirement ")):
            include = line.split(maxsplit=1)[1].strip()
            names.extend(parse_direct_requirements(path.parent / include, seen))
            continue
        if line.startswith("-"):
            continue
        match = REQUIREMENT_RE.match(line)
        if match:
            names.append(canonical(match.group("name")))
    return names


def iter_distribution_requirements(dist_name: str) -> Iterator[str]:
    """Yield canonical names of a distribution's dependencies that apply here.

    PEP 508 environment markers are evaluated against the *current*
    interpreter so that platform- or version-specific extras (``tzdata`` on
    Windows, ``exceptiongroup`` on Python < 3.11, ``importlib-metadata`` on
    old Pythons) do not leak into a lock intended for this target.
    """
    try:
        dist = distribution(dist_name)
    except PackageNotFoundError:
        return
    for raw in dist.requires or ():
        try:
            requirement = Requirement(raw)
        except InvalidRequirement:
            continue
        if requirement.marker is not None and not requirement.marker.evaluate():
            continue
        yield canonical(requirement.name)


def resolve_closure(roots: list[str]) -> dict[str, str]:
    """Breadth-first closure over installed distributions."""
    resolved: dict[str, str] = {}
    queue = list(roots)
    missing: list[str] = []

    while queue:
        name = queue.pop(0)
        if name in resolved:
            continue
        try:
            dist = distribution(name)
        except PackageNotFoundError:
            missing.append(name)
            continue
        resolved[name] = dist.version
        queue.extend(iter_distribution_requirements(name))

    if missing:
        raise SystemExit(
            "ERROR: the following requirements are not installed in this "
            "environment:\n  - " + "\n  - ".join(sorted(missing))
        )
    return resolved


def render(closure: dict[str, str], source_in: Path, target_txt: Path) -> int:
    lines = [
        "# AUTO-GENERATED by scripts/lock_requirements.py - DO NOT EDIT BY HAND.",
        f"# Source: {source_in.relative_to(REPO_ROOT)}",
        "#",
        "# Regenerate after changing any .in file:",
        "#     python scripts/lock_requirements.py",
        "#",
        f"# {len(closure)} pinned distributions.",
        "",
    ]
    for name in sorted(closure):
        lines.append(f"{name}=={closure[name]}")
    lines.append("")
    target_txt.write_text("\n".join(lines), encoding="utf-8")
    return len(closure)


def main() -> int:
    targets = {
        "base": REPO_ROOT / "requirements" / "base.in",
        "dev": REPO_ROOT / "requirements" / "dev.in",
    }
    for target, source_in in targets.items():
        roots = parse_direct_requirements(source_in)
        closure = resolve_closure(roots)
        target_txt = REPO_ROOT / "requirements" / f"{target}.txt"
        count = render(closure, source_in, target_txt)
        print(f"{target_txt.relative_to(REPO_ROOT)}: {count} pinned distributions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
